# Generated by Django 3.2.7 on 2023-08-23 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogvisit',
            old_name='product',
            new_name='blog',
        ),
    ]
